### ISSUE TITLE
No module named 'python_ncc'

### ISSUE THREAD

**Issue by JudasDie** [votchallenge/integration#1]
Hi,
After configuring the new toolkit following the [tutorial](http://www.votchallenge.net/howto/tutorial_python.html), it raises an error "No module named 'python_ncc'" when I run the tracker. Could you kindly help me to fix it?
Here is the configuration file,
![image](https://user-images.githubusercontent.com/24988988/76285959-3abaf400-625e-11ea-9d0b-ea1c16734413.png)

**Comment by alanlukezic** [comment]
Hi, 
it looks like the problem is in <>, which should be deleted.

**Comment by JudasDie** [comment]
> Hi,
> it looks like the problem is in <>, which should be deleted.

Thanks.
After fixing this, the NCC tracker runs on a dummy video. But I couldn't find where it saves the results or downloads videos. Is this normal?

![image](https://user-images.githubusercontent.com/24988988/76318590-2ba66700-629b-11ea-9bea-80f2db659858.png)

**Comment by alanlukezic** [comment]
This is the output of the vot test command, which only tests if a tracker is successfully integrated to the toolkit - it just runs the tracker on a dummy sequence and it does not save results on a disk. If you want to run your tracker on the vot sequences you need to run the vot evaluate command:

vot evaluate --workspace <workspace-path> <tracker-name>

The results are saved in the results folder in vot-workspace directory.

**Comment by JudasDie** [comment]
> This is the output of the vot test command, which only tests if a tracker is successfully integrated to the toolkit - it just runs the tracker on a dummy sequence and it does not save results on a disk. If you want to run your tracker on the vot sequences you need to run the vot evaluate command:
> 
> vot evaluate --workspace
> 
> The results are saved in the results folder in vot-workspace directory.

Thanks a lot!
