### ISSUE TITLE
python_ncc_mask.py can not use

### ISSUE THREAD

**Issue by Naughty-Galileo** [votchallenge/integration#4]
AttributeError: 'MultiObjectTrackerRuntime' object has no attribute '_runtime'

**Comment by lukacu** [comment]
Yes, the tracker that you are trying to run is single-object tracker and cannot be applied to multiple object tracking experiments at the moment. Use python_ncc.py as an example of multi-object tracking.

**Comment by imadtoubal** [comment]
I think the problem is that you're trying to access `self._runtime` before even assigning it. This can be fixed by changing `vot.tracker.MultiObjectTrackerRuntime`, line 554 from:
```
        if self._runtime.multiobject:
```
to
```
        if runtime.multiobject:
```

Please open this issue again since it does not seem resolved.
