### ISSUE TITLE
Several undefined symbols in vot.h for native trackers

### ISSUE THREAD

**Issue by RobotVisionTsai** [votchallenge/integration#5]
Dear all,

I am trying to build a native tracker for evaluation in VOTS2023.
However, when I include vot.h from the integration module, I get several compiling errors about undefined symbols, such as  "trax_object_list" at line 783, "trax_object_list_count" at line 832, "trax_object_list_get" at line 833, etc.

Some trax functions used in vot.h do not have the same parameter declaration defined in trax.h. For example, at line 804 in vot.h,
trax_metadata* metadata = trax_metadata_create(region_format, TRAX_IMAGE_PATH, channels, NULL, NULL, NULL, flags);  
The trax_metadata_create function uses 7 parameters; however, at lines 201-202 in trax.h, this function only defines 6 parameters as follows:
__TRAX_EXPORT trax_metadata* trax_metadata_create(int region_formats, int image_formats, int channels, const char* tracker_name, const char* tracker_description, const char* tracker_family);

Can someone suggest how to deal with this issue?
Thanks in advance.

**Comment by lukacu** [comment]
Which version of trax library are you linking against? From what you are describing it may be an old version that did not have multiobject support.

**Comment by RobotVisionTsai** [comment]
Hi, Lukacu,

I used the newest version of trax library (4.0.0), and it's the master branch of the repo.
When switching to the dev branch of the repo, it works!!
Now, I am doing the evaluation of the native tracker based on the dev version of the trax 4.0.0 lib.
Thanks a lot for your reply!

**Comment by lukacu** [comment]
Yes, I have noticed today that I have not merged recent changes into main branch. Sorry for that, it is done now.
